package com.prakash.pmusic.service

import android.content.Context
import android.media.audiofx.Equalizer
import android.util.Log
import com.prakash.pmusic.domain.model.EqualizerBand
import com.prakash.pmusic.domain.model.EqualizerState
import com.prakash.pmusic.domain.repository.PreferencesRepository
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

/**
 * Equalizer backed by [android.media.audiofx.Equalizer].
 *
 * The effect binds to the player's live audio session. [PlaybackService]
 * generates a session id and assigns it to its ExoPlayer, then reports it
 * here through [setAudioSessionId]. A valid session id lets the effect attach
 * as soon as it is known (even before a track is audible); creation is
 * retried on the first ready/playing report and whenever the id changes as a
 * safety net. The engine always exposes the device band layout (probed on the
 * global output session) so the screen renders and accepts changes that are
 * applied once the effect is bound.
 *
 * The engine is the single owner of the curve: the UI mutates it through the
 * domain [com.prakash.pmusic.domain.repository.PlaybackController], and every
 * change is persisted through [PreferencesRepository] so the curve is
 * re-applied on the next launch. Devices without an equalizer effect report
 * [EqualizerState.supported] as false and the screen renders a fallback.
 */
@Singleton
class AudioFxEqualizerEngine @Inject constructor(
    @ApplicationContext context: Context,
    private val preferencesRepository: PreferencesRepository
) {

    companion object {
        /** Sentinel for "no session known yet" (Media3 C.AUDIO_SESSION_ID_UNSET). */
        private const val SESSION_ID_UNSET = -1

        private const val TAG = "PMusicEqualizer"
    }

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)

    private val _state = MutableStateFlow(EqualizerState())
    val state: StateFlow<EqualizerState> = _state.asStateFlow()

    private var effect: Equalizer? = null

    /**
     * The audio session the effect targets. [PlaybackService] assigns the
     * player a session generated by AudioManager.generateAudioSessionId() and
     * reports it here; the value is also refreshed from
     * Player.Listener.onAudioSessionIdChanged as a safety net.
     */
    private var sessionId: Int = SESSION_ID_UNSET

    // Last persisted snapshot, kept so the curve can be re-applied when the
    // effect (re)binds after playback starts.
    private var lastEnabled = false
    private var lastGains: List<Int> = emptyList()
    private var lastPresetIndex = -1

    init {
        scope.launch {
            preferencesRepository.preferences.collect { prefs ->
                lastEnabled = prefs.equalizerEnabled
                lastGains = prefs.equalizerBandGainsMb
                lastPresetIndex = prefs.equalizerPresetIndex
                probeLayoutIfNeeded()
                applyPersisted(prefs.equalizerEnabled, prefs.equalizerBandGainsMb, prefs.equalizerPresetIndex)
            }
        }
    }

    /**
     * Called when the player reports a ready/playing state. Safety net that
     * binds the effect the first time a valid session id is available.
     */
    fun notifyPlaybackActive() {
        if (effect != null) return
        if (ensureEffect() != null) {
            applyPersisted(lastEnabled, lastGains, lastPresetIndex)
        }
    }

    /**
     * Points the effect at the audio session the player actually created.
     * Called by [PlaybackService] once the player is assigned a generated
     * session id, and again from Player.Listener.onAudioSessionIdChanged as a
     * safety net. Re-binds the real effect when the id changes.
     */
    fun setAudioSessionId(sessionId: Int) {
        if (sessionId <= 0 || sessionId == this.sessionId) return
        Log.i(TAG, "setAudioSessionId($sessionId) re-binding effect")
        this.sessionId = sessionId
        effect?.let {
            runCatching { it.release() }
            effect = null
        }
        if (ensureEffect() != null) {
            applyPersisted(lastEnabled, lastGains, lastPresetIndex)
        }
    }

    /** Turns the equalizer on or off. Persisted so it survives restarts. */
    fun setEnabled(enabled: Boolean) {
        effect?.let { runCatching { it.enabled = enabled } }
        if (_state.value.enabled != enabled) {
            _state.update { it.copy(enabled = enabled) }
            scope.launch { preferencesRepository.setEqualizerEnabled(enabled) }
        }
    }

    /** Sets [band]'s gain to [gainMb] millibels, switching to a custom curve. */
    fun setBandGain(band: Int, gainMb: Int) {
        val current = _state.value
        if (!current.supported || band !in current.bands.indices) return
        val clamped = gainMb.coerceIn(current.minGainMb, current.maxGainMb)
        effect?.let { runCatching { it.setBandLevel(band.toShort(), clamped.toShort()) } }
        val bands = current.bands
            .mapIndexed { index, b -> if (index == band) b.copy(gainMb = clamped) else b }
        _state.update { it.copy(bands = bands, selectedPresetIndex = -1) }
        persistCurve()
    }

    /** Applies the device preset at [presetIndex]. */
    fun selectPreset(presetIndex: Int) {
        val current = _state.value
        if (!current.supported || presetIndex !in current.presetNames.indices) return
        effect?.let { runCatching { it.usePreset(presetIndex.toShort()) } }
        val gains = effect?.let(::readGains)
        _state.update {
            it.copy(
                selectedPresetIndex = presetIndex,
                bands = if (gains != null) {
                    it.bands.mapIndexed { index, b -> b.copy(gainMb = gains.getOrNull(index) ?: b.gainMb) }
                } else {
                    it.bands
                }
            )
        }
        persistCurve()
    }

    /** Resets every band to neutral and clears the preset selection. */
    fun reset() {
        val current = _state.value
        if (!current.supported) return
        val neutral = current.defaultGainMb
        effect?.let { engine ->
            current.bands.indices.forEach { band ->
                runCatching { engine.setBandLevel(band.toShort(), neutral.toShort()) }
            }
        }
        _state.update {
            it.copy(
                bands = it.bands.map { b -> b.copy(gainMb = neutral) },
                selectedPresetIndex = -1
            )
        }
        persistCurve()
    }

    /** Writes the current curve (gains + preset index) to DataStore. */
    private fun persistCurve() {
        scope.launch {
            val snapshot = _state.value
            preferencesRepository.setEqualizerBandGainsMb(snapshot.bands.map { it.gainMb })
            preferencesRepository.setEqualizerPresetIndex(snapshot.selectedPresetIndex)
        }
    }

    /**
     * Populates the state with the device band/preset layout by probing the
     * global output session, which is always active. The probe effect is
     * released immediately; the real effect binds to the player's session
     * once audio is actually playing.
     */
    private fun probeLayoutIfNeeded() {
        if (_state.value.supported) return
        val probe = runCatching { Equalizer(0, 0) }.getOrNull()
        if (probe == null) {
            Log.w(TAG, "probeLayoutIfNeeded() no Equalizer effect on this device")
            return
        }
        val range = probe.bandLevelRange
        val bandCount = probe.numberOfBands.toInt()
        // getCenterFreq returns millihertz; convert to Hz for the UI.
        val frequencies = (0 until bandCount).map { probe.getCenterFreq(it.toShort()) / 1000 }
        val presets = (0 until probe.numberOfPresets.toInt())
            .map { probe.getPresetName(it.toShort()) }
        val gains = readGains(probe)
        val bands = gains.mapIndexed { index, gainMb ->
            EqualizerBand(frequencyHz = frequencies.getOrElse(index) { 0 }, gainMb = gainMb)
        }
        probe.release()
        _state.update {
            it.copy(
                supported = true,
                minGainMb = range[0].toInt(),
                maxGainMb = range[1].toInt(),
                bands = bands,
                presetNames = presets
            )
        }
        Log.i(TAG, "probeLayoutIfNeeded() device layout: $bandCount bands, ${presets.size} presets")
    }

    /**
     * Creates the effect bound to the player's audio session. Returns null
     * only if no valid session id is known yet.
     */
    private fun ensureEffect(): Equalizer? {
        effect?.let { return it }
        val created = runCatching { Equalizer(0, sessionId) }.getOrNull()
        if (created == null) {
            Log.d(TAG, "ensureEffect() session $sessionId not ready yet")
            return null
        }
        Log.i(TAG, "ensureEffect() bound to session $sessionId")
        effect = created
        return created
    }

    /**
     * Re-applies the persisted curve to the effect. Idempotent against the
     * current state so the preferences collector can re-emit the same snapshot
     * without disturbing a live drag.
     */
    private fun applyPersisted(enabled: Boolean, gains: List<Int>, presetIndex: Int) {
        val current = _state.value
        if (!current.supported) return
        val engine = ensureEffect() ?: return

        val gainsMatch = gains.size == current.bands.size &&
            gains.indices.all { index -> gains[index] == current.bands[index].gainMb }
        if (gainsMatch && enabled == current.enabled && presetIndex == current.selectedPresetIndex) {
            return
        }

        if (presetIndex in current.presetNames.indices) {
            runCatching { engine.usePreset(presetIndex.toShort()) }
        } else if (gains.isNotEmpty()) {
            current.bands.indices.forEach { band ->
                val value = gains.getOrNull(band)
                if (value != null) {
                    runCatching {
                        engine.setBandLevel(
                            band.toShort(),
                            value.coerceIn(current.minGainMb, current.maxGainMb).toShort()
                        )
                    }
                }
            }
        }
        runCatching { engine.enabled = enabled }

        val applied = readGains(engine)
        _state.update {
            it.copy(
                enabled = enabled,
                bands = it.bands.mapIndexed { index, b ->
                    b.copy(gainMb = applied.getOrNull(index) ?: b.gainMb)
                },
                selectedPresetIndex = if (presetIndex in it.presetNames.indices) presetIndex else -1
            )
        }
    }

    private fun readGains(engine: Equalizer): List<Int> =
        (0 until engine.numberOfBands.toInt()).map { engine.getBandLevel(it.toShort()).toInt() }
}
